;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Gameplay\\Weapon\\Scannable",NewTagName="Scannable")
+GameplayTagRedirects=(OldTagName="Scannable",NewTagName="Gameplay.Weapons.Scannable")
+GameplayTagList=(Tag="Gameplay.Resource.Crystal",DevComment="")
+GameplayTagList=(Tag="Gameplay.Resource.Metal",DevComment="")
+GameplayTagList=(Tag="Gameplay.Resource.Plant",DevComment="")
+GameplayTagList=(Tag="Gameplay.Targets.Destructible",DevComment="")
+GameplayTagList=(Tag="Gameplay.Targets.Enemy",DevComment="")
+GameplayTagList=(Tag="Gameplay.Targets.Player",DevComment="")
+GameplayTagList=(Tag="Gameplay.Weapons.Scannable",DevComment="")
+GameplayTagList=(Tag="Gameplay.Weapons.Tractorable",DevComment="")

